services:
  database:
    container_name: corebiz-database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: corebiz_db
    ports:
      - "5432:5432"

  server:
    container_name: corebiz-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host
    volumes:
      - ./src:/app/src
    depends_on:
      - database
